baseURL = "https://jinfinance.github.io"
#baseURL = "http://localhost:1313/"

languageCode = "en-us"
title = "My Personal Site"
theme = "PaperMod"

[params]
  author = "Your Name"
  ShowReadingTime = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

